config/routes.rb
Rails.application.routes.draw do

  resources :profiles
  get 'welcome/index'

  get 'reviews', to: 'reviews#index'
  post 'reviews', to: 'reviews#create'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  

  resources :playlists do
    member do
      post 'upvote'
      post 'downvote'
      get 'confirmation'
    end
  end
  get 'playlists', to: 'playlists#index', page: 1
  get 'playlists/page/:page', to: 'playlists#index'

  root to: 'welcome#index'

  get 'facebook/token'

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  validates :url, :name, presence: true
  has_many :reviews
  has_many :votes, dependent: :destroy
  has_many :downvotes, dependent: :destroy
  belongs_to :user
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: [:show, :confirmation, :edit, :update, :destroy]

  # GET /playlists
  # GET /playlists.json
  def index
    @page = (params[:page] || 1).to_i
    @offset = (@page - 1) * 8
    @playlists = Playlist.
      order(created_at: :desc).
      limit(8).
      offset(@offset).
      all
  end

  # GET /playlists/1
  # GET /playlists/1.json
  def show
    @review = Review.new
  end

  def confirmation
    @review = Review.new
  end

  # GET /playlists/new
  def new
    @playlist = Playlist.new
  end

  # GET /playlists/1/edit
  def edit
  end

  # POST /playlists
  # POST /playlists.json
  def create
    @playlist = Playlist.new(playlist_params)
    @playlist.user = current_user
    respond_to do |format|
      if @playlist.save
        format.html { redirect_to confirmation_playlist_path(@playlist), notice: 'Playlist was successfully created.' }
        format.json { render :show, status: :created, location: @playlist }
      else
        format.html { render :new }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /playlists/1
  # PATCH/PUT /playlists/1.json
  def update
    respond_to do |format|
      if @playlist.update(playlist_params)
        format.html { redirect_to confirmation_playlist_path(@playlist), notice: 'Playlist was successfully updated.' }
        format.json { render :show, status: :ok, location: @playlist }
      else
        format.html { render :edit }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists/1
  # DELETE /playlists/1.json
  def destroy
    @playlist.destroy
    respond_to do |format|
      format.html { redirect_to playlists_url, notice: 'Playlist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @playlist = Playlist.find(params[:id])
    @playlist.votes.create
    redirect_to(playlists_path)
  end

  def downvote
    @playlist = Playlist.find(params[:id])
    @playlist.downvotes.create
    redirect_to(playlists_path)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_playlist
      @playlist = Playlist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def playlist_params
      params.require(:playlist).permit(:name, :url, :image, :description, :comment)
    end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/_form.html.erb
<%= form_for(@playlist) do |f| %>
  <% if @playlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@playlist.errors.count, "error") %> prohibited this playlist from being saved:</h2>

      <ul>
      <% @playlist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <label for="playlist_image">Image URL</label><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <label for="playlist_url">Playlist URL</label><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <!-- <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div> -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/playlists/confirmation.html.erb
<p id="notice"><%= notice %></p>

<p class="show_sections">
  <strong>This is your last chance to edit or destroy this playlist!</strong>
</p>

<p class="show_sections">
  <strong>Name:</strong>
  <%= @playlist.name %>
</p>

<p class="show_sections">
  <!-- <strong>Image:</strong> -->
  <% if (@playlist.image == "") %>
    <img class="image_show" src='http://www.ketlis.com/images/blue_play_button.png' alt:<%= @playlist.name %> >
  <% else %>
    <img class="image_show" src=<%= @playlist.image %> alt:<%= @playlist.name %> >
  <% end %>
</p>

<p class="show_sections">
  <strong>Playlist URL:</strong>
  <a href=<%= @playlist.url %>><%= @playlist.url %></a>
</p>

<% if !(@playlist.description == "") %>
  <p class="description show_sections">
      <strong>Description:</strong>
      <%= @playlist.description %>
  </p>
<% end %>

<!-- <p class="show_sections">
  <strong>Comment:</strong>
  <%= @playlist.comment %>
</p> -->
<div class="comment">
  <h3 class="new_review_head">New Review</h3>
</div>
<%= render 'reviews/form' %>

<h3>Reviews:</h3>

<% @playlist.reviews.each do |review| %>
  <div class="comment show_sections">
    <%= review.comment %>
    <br>
    <p class="timestamp">Added on: <%= review.created_at %></p>
  </div>
<% end %>

<div class="home_and_edit">
  <%= link_to 'Edit', edit_playlist_path(@playlist) %> |
  <%= link_to 'Destroy', @playlist, method: :delete, data: { confirm: 'Are you sure?' } %> |
  <%= link_to 'Home', playlists_path %>
</div>

app/views/playlists/edit.html.erb
<h1>Editing Playlist</h1>

<%= render 'form' %>

<%= link_to 'Show', @playlist %> |
<%= link_to 'Back', playlists_path %>

app/views/playlists/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Feed</h1>

<div class="entries">
  <% @playlists.each do |playlist| %>
  <div class="entry">
    <h3 class="title">
      <%= playlist.name %>
    </h3>
    <div>
      <% if (playlist.image === "") %>
        <a class="image_link" href=<%= "/playlists/#{playlist.id}" %>><img class="image_home" src='http://www.ketlis.com/images/blue_play_button.png' alt:<%= playlist.name %> ></a>
      <% else %>
        <a class="image_link" href=<%= "/playlists/#{playlist.id}" %>><img class="image_home" src=<%= playlist.image %> alt:<%= playlist.name %> ></a>
      <% end %>
    </div>
    <p>
      <%= pluralize((playlist.votes.count-playlist.downvotes.count), "vote") %>
      <div class="voters">
        <%= button_to '/\\', upvote_playlist_path(playlist), method: :post %>
        <%= button_to '\\/', downvote_playlist_path(playlist), method: :post %>
      </div>
    </p>
  </div>
  <!-- <div class="more-btn-container"> -->
    <!-- <a class="more-btn" href="#">More</a> -->
    <!-- <ul class="more-menu"> -->
      <!-- <li><%= link_to 'Show', playlist %></li> -->
      <!-- <li><%= link_to 'Edit', edit_playlist_path(playlist) %></li> -->
      <!-- <li><%= link_to 'Destroy', playlist, method: :delete, data: { confirm: 'Are you sure?' } %></li> -->
    <!-- </ul> -->
  <!-- </div> -->
<% end %>
</div>
<br/>
<div class="clearing">
  <div class="page_nav">
    <ul class="page_nav_list">
      <% unless (@page == 1) %>
        <li class="page_nav_link"><%= link_to 'Previous page', page: @page - 1 %></li>
      <% end %>
      <% unless ((@page * @offset)>=(Playlist.all.length)) %>
        <li class="page_nav_link"><%= link_to 'Next page', page: @page + 1 %></li>
      <% end %>
    </ul>
  </div>

</div>




<!-- <table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>Image</th>
      <th>Description</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @playlists.each do |playlist| %>
      <tr>
        <td><%= playlist.name %></td>
        <td><%= playlist.url %></td>
        <td><%= image_tag playlist.image %></td>
        <td><%= playlist.description %></td>
        <td><%= playlist.comment %></td>
        <td><%= link_to 'Show', playlist %></td>
        <td><%= link_to 'Edit', edit_playlist_path(playlist) %></td>
        <td><%= link_to 'Destroy', playlist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table> -->

<!-- <br>
<p class="new_link">
  <%= link_to 'New Playlist', new_playlist_path %>
</p> -->

app/views/playlists/new.html.erb
<h1>New Playlist</h1>

<%= render 'form' %>

<div class="new_back">
  <%= link_to 'Back', playlists_path %>
</div>

app/views/playlists/show.html.erb
<!-- <ul class="nav_bar">
  <li class="soundbaselogo">
    <%= link_to 'SoundBase', welcome_index_path %>
  </li>
  <li class="home_link">
    <%= link_to 'Feed', playlists_path %>
  </li>
  <li class="new_link">
    <%= link_to 'New Playlist', new_playlist_path %>
  </li>
  </ul> -->

<p id="notice"><%= notice %></p>

<h2 class="show_sections">
  <%= @playlist.name %>
</h2>

<p class="show_sections">
  <!-- <strong>Image:</strong> -->
  <% if (@playlist.image == "") %>
    <img class="image_show" src='http://www.ketlis.com/images/blue_play_button.png' alt:<%= @playlist.name %> >
  <% else %>
    <img class="image_show" src=<%= @playlist.image %> alt:<%= @playlist.name %> >
  <% end %>
</p>

<p class="show_sections">
  <strong>Playlist URL:</strong>
  <a href=<%= @playlist.url %>><%= (@playlist.url).truncate(43) %></a>
</p>

<% if !(@playlist.description == "") %>
  <p class="description show_sections">
      <strong>Description:</strong>
      <%= @playlist.description %>
  </p>
<% end %>

<!-- <p class="show_sections">
  <strong>Comment:</strong>
  <%= @playlist.comment %>
</p> -->
<div class="comment">
  <h3 class="new_review_head">New Review</h3>
</div>
<%= render 'reviews/form' %>

<h3>Reviews:</h3>

<% @playlist.reviews.each do |review| %>
  <div class="comment show_sections">
    <%= review.comment %>
    <br>
    <p class="timestamp">Added on: <%= review.created_at %></p>
  </div>
<% end %>

<div class="home_and_edit">
  <!-- <% if (notice == "Playlist was successfully created.") || (notice == "Playlist was successfully updated.") %>
    <%= link_to 'Edit', edit_playlist_path(@playlist) %> |
    <%= link_to 'Destroy', @playlist, method: :delete, data: { confirm: 'Are you sure?' } %> |
  <% end %> -->
  <%= link_to 'Home', playlists_path %>
</div>